### ISSUE TITLE
Uninstall after success message?

### ISSUE THREAD

**Issue by gah242s** [civicrm/org.civicrm.doctorwhen#15]
This is a great little extension for us legacy users.  Thank you!  However, it appears that this extension is designed to be a "single use" extension; run it and be done with it kind of thing.  However, I wasn't sure if that fit better in the README.MD, the INSTALL.md, in a Status page message, or all three.

**Comment by totten** [comment]
@gah242s Any or all are good.

Strongest :+1: for adding uninstall as a bulleted task in the README.md -- since this file tries to show the overall workflow for an admin.

Adding a message to the status page is also a good idea for folks who install and then leave it around for no particular reason.

For INSTALL.md... that file delves more into technical details/commands. I think that would only be *needed* if the uninstall process is special/unusual. However, it seems safe/fair to mention standard uninstall steps -- the audience here may include some less-experienced Civi admins.

**Comment by gah242s** [comment]
I've added three simple PR's to give a first round go at adding this to the documentation.

**Comment by totten** [comment]
Cool. I've merged #16 and #18 -- and left some comments on #17.

**Comment by gah242s** [comment]
Updated #17 and probably sufficiently broke it the way I did, but I did it.

**Comment by totten** [comment]
All PR's merged.
